A critical error has ocurred while running the game!
Error type: <class 'AttributeError'>
What happened: 'tuple' object has no attribute 'event'
Where it happened:  file 'd:\Documentos\Programas\C\nundertale\main.py', at line 33Why it happned: Bad coding xD

Full error traceback:
 Traceback (most recent call last):
  File "d:\Documentos\Programas\C\nundertale\main.py", line 33, in main
    controller.main_loop()
  File "d:\Documentos\Programas\C\nundertale\controller\GameController.py", line 29, in main_loop
    self.get_update_events()
  File "d:\Documentos\Programas\C\nundertale\controller\GameController.py", line 16, in get_update_events
    self.__events = self.view.get_events()
  File "d:\Documentos\Programas\C\nundertale\view\GameView.py", line 30, in get_events
    return self.game.event
AttributeError: 'tuple' object has no attribute 'event'
